// The comparator the WINDOW runs must be the comparator the engine runs.
//
// desktop/ui/update-compare.js is transpiled from src/update/compare.ts
// because the webview has no build step and cannot import TypeScript.
// Two different things can go wrong with that arrangement and this file
// checks both:
//
//   1. The committed file is stale. Someone edits compare.ts, the tests
//      there pass, and the window keeps running last week's rule.
//   2. The transpile changed behaviour. Much less likely, and much worse,
//      because every test in update-compare.test.ts would still pass
//      while the window answered differently.
//
// The second is why this file re-asks the questions rather than only
// diffing bytes. A byte comparison proves the file is current; it proves
// nothing about what the file DOES.
import { describe, test, expect } from 'bun:test';
import { readFileSync } from 'node:fs';
import {
  renderCompareModule,
  renderCompareTypes,
  TARGET,
  TYPES_TARGET,
} from '../tools/build-update-compare';
import * as engine from '../src/update/compare';
import * as window from '../desktop/ui/update-compare.js';

const committed = readFileSync(TARGET, 'utf8');

describe('the committed module is what the generator produces', () => {
  test('byte for byte', async () => {
    // The stale-checkout check. desktop.yml runs the generator and
    // `git diff --exit-code`s the result for the same reason; this one
    // fails in `bun test`, which is where a person looks first.
    expect(committed).toBe(await renderCompareModule());
  });

  test('it says it is generated, and by what', () => {
    // Someone WILL open this file and start editing it. The header is
    // the only thing that stops them.
    expect(committed.startsWith('// GENERATED by tools/build-update-compare.ts')).toBe(true);
    expect(committed).toContain('src/update/compare.ts');
    expect(committed).toContain('Regenerate with: bun tools/build-update-compare.ts');
  });

  test('no TypeScript survived the trip', () => {
    // A browser loads this directly. A stray type annotation is a syntax
    // error at load, which in a webview means a blank window.
    expect(committed).not.toContain(': string');
    expect(committed).not.toContain('export interface');
    expect(committed).not.toContain('export type');
  });

  test('the type declaration beside it is current too, and is a RE-EXPORT', () => {
    // It must not be the generated JavaScript's types written out. A
    // written-out copy is a second definition of the module's shape and
    // would let an export be added to compare.ts without reaching the
    // window, which is the whole class of bug this generator prevents.
    const types = readFileSync(TYPES_TARGET, 'utf8');
    expect(types).toBe(renderCompareTypes());
    expect(types).toContain("export * from '../../src/update/compare'");
    // No hand-written signatures.
    expect(types).not.toContain('export declare');
    expect(types).not.toContain('export function');
  });

  test('it is readable, because someone will read it to answer a bug report', () => {
    // Not minified. The question this file exists to answer is "why was
    // I offered / not offered that update", and a minified answer is no
    // answer.
    expect(committed.split('\n').length).toBeGreaterThan(40);
  });
});

describe('the window answers the same as the engine', () => {
  // The behavioural half. Every case here is asked of BOTH modules and
  // the answers are compared to each other, not to a hardcoded
  // expectation: the claim under test is "these two agree", and writing
  // the expected value out by hand would let both drift together.
  const pairs: [string, string][] = [
    // the defence, which is the whole reason the window needs this
    ['0.6.0', '0.6.0-1-g965cb10'],
    ['0.6.0', '0.6.0-1-g965cb10-dirty'],
    ['0.6.0', '0.6.0-dirty'],
    ['0.7.0', '0.6.0-1-g965cb10'],
    // ordinary comparisons
    ['0.6.1', '0.6.0'],
    ['0.6.0', '0.6.0'],
    ['0.5.4', '0.6.0'],
    ['0.10.0', '0.9.0'],
    ['1.0.0', '0.99.99'],
    // pre-releases, where describe output must NOT be over-matched
    ['0.6.0', '0.6.0-beta.1'],
    ['0.6.0', '0.3.0-dev'],
    ['0.6.0-beta.10', '0.6.0-beta.9'],
    // normalization
    ['v0.4.0', '0.3.0'],
    ['0.3.0+ci.7', '0.3.0'],
  ];

  test('isNewer agrees on every pair, including the describe cases', () => {
    for (const [candidate, current] of pairs) {
      expect(`${candidate} vs ${current}: ${window.isNewer(candidate, current)}`).toBe(
        `${candidate} vs ${current}: ${engine.isNewer(candidate, current)}`,
      );
    }
    // Non-vacuity: a comparison list that was all-false or all-true
    // would pass the loop above while testing almost nothing.
    const answers = pairs.map(([a, b]) => engine.isNewer(a, b));
    expect(answers).toContain(true);
    expect(answers).toContain(false);
  });

  test('normalizeVersion and isDescribeSuffix agree too', () => {
    for (const [candidate] of pairs) {
      expect(window.normalizeVersion(candidate)).toBe(engine.normalizeVersion(candidate));
    }
    for (const pre of ['1-g965cb10', 'dirty', 'beta.1', 'dev', '1-g', 'x-g965cb10']) {
      expect(`${pre}: ${window.isDescribeSuffix(pre)}`).toBe(
        `${pre}: ${engine.isDescribeSuffix(pre)}`,
      );
    }
  });

  test('pickUpdate agrees, decision and reason', () => {
    const cases = [
      null,
      { version: '0.7.0', currentVersion: '0.6.0' },
      { version: '0.6.0', currentVersion: '0.6.0-1-g965cb10' },
      { version: 'not-a-version', currentVersion: '0.6.0' },
      { version: '0.6.0', currentVersion: '' },
    ];
    for (const c of cases) {
      expect(window.pickUpdate(c)).toEqual(engine.pickUpdate(c));
    }
  });

  test('shouldCheck agrees, including the clock set backwards', () => {
    const now = 1_800_000_000_000;
    const h = (n: number) => n * 3600_000;
    const cases: [boolean, number | undefined, number][] = [
      [false, undefined, now],
      [true, undefined, now],
      [true, now - h(1), now],
      [true, now - h(25), now],
      [true, now + h(1), now],
    ];
    for (const [optedIn, last, t] of cases) {
      expect(window.shouldCheck(optedIn, last, t)).toBe(engine.shouldCheck(optedIn, last, t));
    }
    expect(window.CHECK_INTERVAL_MS).toBe(engine.CHECK_INTERVAL_MS);
  });
});
