// GENERATED by tools/build-desktop-notes.ts — do not edit.
// Source: docs/releases/0.6.0.md
// Regenerate with: bun tools/build-desktop-notes.ts
export const RELEASE = {
  version: "0.6.0",
  headline: "Screepub runs on Linux and Windows now, and the page problem the last release asked you to watch for turned out to be real.",
  sections: [
    {
      title: "Screepub runs where you work",
      items: [
        { lead: "There is a window now, not just a command line.", body: "Install Screepub_0.6.0_amd64.deb or Screepub-0.6.0-1.x86_64.rpm on Linux, Screepub-0.6.0-setup.exe on Windows, or Screepub-Desktop-macOS-universal.dmg on a Mac, one file for both Apple Silicon and Intel. The converter alone still ships for both: unpack and run it." },
        { lead: "The Mac app has not changed.", body: "Screepub-macOS.dmg is the same download, signed by Apple as before, and still the one we support on a Mac. The new window is a separate download." },
        { lead: "Two new commands, and a script that remembers.", body: "screepub devices lists the readers it can see and screepub send copies a finished file onto one. screepub settings saves how you want one script laid out." },
      ],
    },
    {
      title: "Fixed on Kindle",
      items: [
        { lead: "Character names no longer strand at page turns.", body: "0.5.4 asked you to report exactly this, and it was real: the name sat alone at the bottom with its speech overleaf. Confirmed fixed on a Kindle, on the script and the route that produced it." },
      ],
    },
    {
      title: "Good to know",
      items: [
        { lead: "Windows will warn you the first time you run it.", body: "Both Windows downloads are unsigned, so SmartScreen shows a \"publisher unknown\" screen. Choose More info, then Run anyway. The installer also fetches Microsoft's WebView2 runtime if your machine has none. Converting itself never touches the network." },
        { lead: "Sending to a reader has only been tried on a Mac, with a Kindle.", body: "Everything else is code-tested but has never met real hardware. On Windows a tolino cannot be found at all: it is known by its drive's name, and a Windows drive root has none." },
        { lead: "", body: "One person has installed the new window, on one Mac. The .deb, the .rpm and the Windows installer have never been installed by anyone." },
      ],
    },
  ],
};
