// GENERATED by tools/build-desktop-notes.ts — do not edit.
// Source: docs/releases/0.7.4.md
// Regenerate with: bun tools/build-desktop-notes.ts
export const RELEASE = {
  version: "0.7.4",
  headline: "The window makes use of a wide screen. Thinner margins, the scene list beside the script, and a Settings preview you can actually read.",
  sections: [
    {
      title: "Room to read and tune",
      items: [
        { lead: "The page fills a wide window.", body: "It used to stop at a column in the middle, with wide empty margins and the brads drifting toward the center. Now it runs nearly edge to edge, and the brads stay near the left edge, the way the holes sit on a letter page. New windows open at 1280 by 800." },
        { lead: "The scene list sits beside the script.", body: "On Read, it used to slide out over the left margin, on top of the brads. Now it has a column of its own, and showing or hiding it never moves the script." },
        { lead: "A bigger Settings preview.", body: "It is about twice as wide, runs the height of the window, and stays put while you scroll through the settings. Each group of settings sits in its own box." },
      ],
    },
    {
      title: "Good to know",
      items: [
        { lead: "", body: "Under 900 wide the window keeps its narrow layout: the scene list goes above the script, and the preview below the settings." },
      ],
    },
  ],
};
