// GENERATED by tools/build-desktop-notes.ts — do not edit.
// Source: docs/releases/0.5.4.md
// Regenerate with: bun tools/build-desktop-notes.ts
export const RELEASE = {
  version: "0.5.4",
  headline: "Three ways a script could arrive wrong, all found by reading real ones.",
  sections: [
    {
      title: "Your script arrives whole",
      items: [
        { lead: "A song lyric could delete most of the book.", body: "A lyric line's slash, landing next to italics, could open a comment that swallowed everything until the next one. On a 110-page script that removed 63%: 67 of 97 scenes, with no warning at all. If a script has ever seemed to skip a stretch, convert it again." },
        { lead: "Two characters talking at once stay two characters.", body: "Simultaneous speech printed in side-by-side columns could arrive with both names demoted to ordinary text and the two speeches run together into a single sentence, so it read as though one person said both halves." },
      ],
    },
    {
      title: "Pages fill again",
      items: [
        { lead: "A long speech no longer pushes a whole page.", body: "A speech that would not fit in what was left of a page used to move over in one piece, ending the page two thirds of the way down. It splits now, keeping the character name and the opening lines together the way a printed script does." },
      ],
    },
    {
      title: "Good to know",
      items: [
        { lead: "", body: "That last change has been read on a Kindle, but not yet with a very long speech at a large font size. If a character name ever ends up alone at the foot of a page, that is the case worth reporting." },
      ],
    },
  ],
};
