// GENERATED by tools/build-update-compare.ts — do not edit.
// Source: src/update/compare.ts
// Regenerate with: bun tools/build-update-compare.ts
// src/update/compare.ts
function normalizeVersion(version) {
  let v = version.trim();
  if (v.startsWith("v") || v.startsWith("V"))
    v = v.slice(1);
  const plus = v.indexOf("+");
  if (plus !== -1)
    v = v.slice(0, plus);
  return v;
}
function isDescribeSuffix(pre) {
  if (pre === "dirty")
    return true;
  let body = pre;
  if (body.endsWith("-dirty"))
    body = body.slice(0, -"-dirty".length);
  const dash = body.indexOf("-");
  if (dash <= 0)
    return false;
  const count = body.slice(0, dash);
  const hash = body.slice(dash + 1);
  if (!/^[0-9]+$/.test(count))
    return false;
  return /^g[0-9a-f]{4,}$/i.test(hash);
}
function parts(version) {
  const dash = version.indexOf("-");
  const core = dash === -1 ? version : version.slice(0, dash);
  const pre = dash === -1 ? undefined : version.slice(dash + 1);
  const nums = core.split(".").map((p) => Number.parseInt(p, 10));
  return [nums, pre];
}
function isReadable(version) {
  const [nums] = parts(normalizeVersion(version));
  return nums.length > 0 && nums.every((n) => Number.isInteger(n) && n >= 0);
}
function isNewer(candidate, current) {
  const [candNums, candPre] = parts(normalizeVersion(candidate));
  const [currNums, currPre] = parts(normalizeVersion(current));
  const width = Math.max(candNums.length, currNums.length);
  for (let i = 0;i < width; i++) {
    const a = i < candNums.length ? candNums[i] : 0;
    const b = i < currNums.length ? currNums[i] : 0;
    if (a !== b)
      return a > b;
  }
  if (candPre === undefined && currPre === undefined)
    return false;
  if (candPre === undefined && currPre !== undefined)
    return !isDescribeSuffix(currPre);
  if (candPre !== undefined && currPre === undefined)
    return false;
  if (isDescribeSuffix(currPre))
    return false;
  return candPre.localeCompare(currPre, undefined, { numeric: true }) > 0;
}
function pickUpdate(candidate) {
  if (candidate === null)
    return { offer: false, reason: "no update was reported" };
  const { version, currentVersion } = candidate;
  if (!isReadable(version) || !isReadable(currentVersion)) {
    return {
      offer: false,
      reason: `could not read the versions: offered ${JSON.stringify(version)}, ` + `running ${JSON.stringify(currentVersion)}`
    };
  }
  if (!isNewer(version, currentVersion)) {
    return {
      offer: false,
      reason: `${version} is not newer than the running ${currentVersion}`
    };
  }
  return { offer: true, version };
}
var CHECK_INTERVAL_MS = 24 * 60 * 60 * 1000;
function shouldCheck(optedIn, lastChecked, now) {
  if (!optedIn)
    return false;
  if (lastChecked === undefined)
    return true;
  return now - lastChecked >= CHECK_INTERVAL_MS;
}
export {
  shouldCheck,
  pickUpdate,
  normalizeVersion,
  isNewer,
  isDescribeSuffix,
  CHECK_INTERVAL_MS
};
