// GENERATED by tools/build-update-compare.ts — do not edit.
// Source: src/update/compare.ts
// Regenerate with: bun tools/build-update-compare.ts
// Not the generated JavaScript's types written out, but a re-export of
// the engine module's. The claim is that these two have the same shape,
// so the declaration says exactly that and cannot drift from it.
export * from '../../src/update/compare';
