// desktop/ui/update-compare.js, transpiled from src/update/compare.ts.
//
// The window has no build step: tauri.conf.json says
// `frontendDist: "../ui"` and every import in desktop/ui is a relative
// `./` ES module, so the webview cannot import TypeScript from src/.
// This is how engine logic crosses that gap, and it is the same pattern
// tools/build-desktop-notes.ts already uses for the release notes.
//
// Why the updater needs it. The Tauri plugin decides "is there an
// update?" with semver, and semver is wrong about a build past a tag:
// `0.6.0-1-g965cb10` reads as a pre-release BELOW 0.6.0, so the plugin
// offers 0.6.0 and installs a downgrade. The engine's comparator knows
// better. For the window to apply that second opinion, the comparator
// has to be reachable from the window, and it must be THE SAME code
// rather than a second copy that can drift.
//
// TRANSPILED, not re-implemented, which is the whole point. A
// hand-written JavaScript twin of compare.ts would be a second
// definition of the downgrade rule, and this repository has a name for
// what happens then: the cue definition existed twice, the two
// disagreed, and a script whose lead was named "Q" lost a dual-dialogue
// scene. One definition, mechanically copied.
//
// tests/update-compare-module.test.ts asserts the committed file is
// exactly what this produces, AND that it answers the same as the
// TypeScript on the cases that matter. The first catches a stale
// checkout; the second catches a transpile that changed behaviour.
// desktop.yml re-runs this and `git diff --exit-code`s the result, the
// same as it does for notes.js and tokens.css.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { REPO_DIR } from './build-cli';

export const SOURCE = 'src/update/compare.ts';
export const TARGET = join('desktop', 'ui', 'update-compare.js');
export const TYPES_TARGET = join('desktop', 'ui', 'update-compare.d.ts');

const HEADER = [
  `// GENERATED by tools/build-update-compare.ts — do not edit.`,
  `// Source: ${SOURCE}`,
  `// Regenerate with: bun tools/build-update-compare.ts`,
  '',
].join('\n');

/** Transpile the comparator to a browser ES module.
 *
 *  `target: browser` and `format: esm` because that is what the webview
 *  loads. No minification: this file is read by people looking for why
 *  an update was or was not offered, and a minified answer to that
 *  question is no answer.
 *
 *  Output shape depends on the bun version, which is why ci.yml and
 *  release.yml pin one. A bump regenerates this file, the diff shows up,
 *  and that is the intended behaviour rather than a nuisance. */
export async function renderCompareModule(repoDir: string = REPO_DIR): Promise<string> {
  const built = await Bun.build({
    entrypoints: [join(repoDir, SOURCE)],
    target: 'browser',
    format: 'esm',
    minify: false,
  });
  if (!built.success || built.outputs.length !== 1) {
    const logs = built.logs.map((l) => String(l)).join('\n');
    throw new Error(
      `build-update-compare: expected exactly one output from ${SOURCE}, got ` +
        `${built.outputs.length}${logs ? `\n${logs}` : ''}`,
    );
  }
  const code = await built.outputs[0]!.text();
  return HEADER + code;
}

/** The type declaration beside it, which is a RE-EXPORT of the engine's
 *  own types rather than a written-out copy.
 *
 *  That is the whole trick: the declaration does not describe the
 *  generated JavaScript, it asserts that the generated JavaScript has
 *  the same shape as the module it was transpiled from. Add an export to
 *  compare.ts and this needs no edit; write the types out by hand and it
 *  becomes the second definition this generator exists to avoid.
 *
 *  Never loaded by the browser. TypeScript reads it; the webview does
 *  not. */
export function renderCompareTypes(): string {
  return (
    HEADER +
    [
      '// Not the generated JavaScript\'s types written out, but a re-export of',
      "// the engine module's. The claim is that these two have the same shape,",
      '// so the declaration says exactly that and cannot drift from it.',
      "export * from '../../src/update/compare';",
      '',
    ].join('\n')
  );
}

if (import.meta.main) {
  writeFileSync(join(REPO_DIR, TARGET), await renderCompareModule());
  writeFileSync(join(REPO_DIR, TYPES_TARGET), renderCompareTypes());
  console.log(`wrote ${TARGET} and ${TYPES_TARGET} from ${SOURCE}`);
}
