// desktop/ui/tokens.css, generated from brand/tokens.json and the scale
// blocks of brand/tokens.css.
//
// Why a generated copy and not an @import: desktop/ui has no build step and
// tauri.conf.json's frontendDist embeds only what is under desktop/ui/, so a
// path into brand/ 404s even under `cargo run`. The copy is therefore
// unavoidable; a copy a person maintains is not. tests/desktop-tokens.test.ts
// regenerates this file and fails on any difference.
//
// The seven colours in CORE_IN_STYLE_CSS are deliberately EXCLUDED: they live
// in desktop/ui/style.css, where tests/desktop-shell.test.ts pins them to
// brand/tokens.json in its own way. Declaring them twice would create a
// "which block wins" question with no good answer.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const CORE_IN_STYLE_CSS = [
  'paper', 'ink', 'ink-muted', 'ink-on-brass', 'brass', 'ground', 'alarm',
] as const;

const HEADER = `/* GENERATED by tools/build-desktop-tokens.ts — do not edit.
 * Source of truth: brand/tokens.json (colours) and brand/tokens.css (scales).
 * The seven colours desktop/ui/style.css declares are excluded on purpose;
 * see the generator for why. Regenerate with:
 *   bun tools/build-desktop-tokens.ts
 */
`;

/** The non-colour blocks, lifted verbatim from brand/tokens.css so the two
 *  files cannot describe different scales. Keyed by the comment that opens
 *  each block there. */
const SCALE_MARKERS = [
  '--font-structure:',
  '--text-fine:',
  '--radius-mark:',
  '--motion-press:',
  '--space-1:',
  '--measure:',
];

function scaleLines(brandCss: string, colorNames: Set<string>): string[] {
  const root = brandCss.slice(brandCss.indexOf(':root'), brandCss.indexOf('@media'));
  const lines: string[] = [];
  for (const line of root.split('\n')) {
    const declaration = line.trim();
    // Matches up to the FIRST `;`, not anchored to end-of-line: several
    // declarations here (the whole --text-* and --radius-* blocks) carry a
    // trailing `/* comment */` after the semicolon, e.g.
    // `--text-fine: 10px;      /* "or", constraint lines */`. An
    // end-anchored regex (`;$`) silently drops every one of those lines,
    // which the SCALE_MARKERS guard below then (correctly) throws on.
    const match = /^--([\w-]+):\s*(.+?);/.exec(declaration);
    if (!match) continue;
    const [, name] = match;
    // Colours come from tokens.json, which is the source of truth for them.
    // Matched by EXACT NAME, never by prefix: `--hole` is a colour and
    // `--hole-center` is a geometry value, and a prefix test would silently
    // drop the second one and put the brads in the wrong place.
    if (colorNames.has(name)) continue;
    lines.push(`  ${declaration}`);
  }
  // Guard the lift: brand/tokens.css moving its scales would otherwise make
  // this generator silently produce a file with no sizes in it.
  for (const marker of SCALE_MARKERS) {
    if (!lines.some((l) => l.includes(marker))) {
      throw new Error(`brand/tokens.css no longer declares ${marker}`);
    }
  }
  return lines;
}

export function buildDesktopTokens(tokensJson: string, brandCss: string): string {
  const colors = JSON.parse(tokensJson).colors as Record<
    string,
    { light: string; dark: string }
  >;
  const excluded = new Set<string>(CORE_IN_STYLE_CSS);
  const names = Object.keys(colors).filter((n) => !excluded.has(n));

  const light = names.map((n) => `  --${n}: ${colors[n].light};`);
  const dark = names
    .filter((n) => colors[n].dark !== colors[n].light)
    .map((n) => `    --${n}: ${colors[n].dark};`);

  return (
    `${HEADER}\n:root {\n` +
    `${light.join('\n')}\n\n` +
    `${scaleLines(brandCss, new Set(Object.keys(colors))).join('\n')}\n` +
    `}\n\n` +
    `@media (prefers-color-scheme: dark) {\n  :root {\n${dark.join('\n')}\n  }\n}\n`
  );
}

if (import.meta.main) {
  const repo = join(import.meta.dir, '..');
  const out = buildDesktopTokens(
    readFileSync(join(repo, 'brand', 'tokens.json'), 'utf8'),
    readFileSync(join(repo, 'brand', 'tokens.css'), 'utf8'),
  );
  writeFileSync(join(repo, 'desktop', 'ui', 'tokens.css'), out);
  console.log('wrote desktop/ui/tokens.css');
}
