// desktop/ui/notes.js, compiled from docs/releases/<version>.md.
//
// The window has no filesystem and no markdown library, and it must work
// offline, so the notes are turned into data at build time. The subset is
// exactly the shape docs/release-notes-template.md produces: one H1, a
// headline paragraph, H2 sections, and bold-led bullets. Anything outside
// that shape is a template change, and this throws rather than dropping it
// silently. tests/desktop-notes.test.ts regenerates and compares.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export interface ReleaseNotes {
  version: string;
  headline: string;
  sections: { title: string; items: { lead: string; body: string }[] }[];
}

const BULLET = /^- \*\*(.+?)\*\*\s*(.*)$/;

/** Strip the inline markup the template uses, leaving the sentence. Code
 *  spans and links keep their TEXT, because the text is the sentence. */
function plain(value: string): string {
  return value
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .trim();
}

export function parseReleaseNotes(version: string, markdown: string): ReleaseNotes {
  const lines = markdown.split('\n');
  let headline = '';
  const sections: ReleaseNotes['sections'] = [];
  let current: ReleaseNotes['sections'][number] | null = null;
  let open: { lead: string; body: string[] } | null = null;

  const closeItem = () => {
    if (open && current) {
      current.items.push({ lead: open.lead, body: plain(open.body.join(' ')) });
    }
    open = null;
  };

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.startsWith('# ')) continue; // the title; version carries it
    if (line.startsWith('## ')) {
      closeItem();
      current = { title: line.slice(3).trim(), items: [] };
      sections.push(current);
      continue;
    }
    const bullet = BULLET.exec(line);
    if (bullet) {
      closeItem();
      open = { lead: plain(bullet[1]), body: [bullet[2]] };
      continue;
    }
    if (open && /^\s+\S/.test(raw)) {
      // A wrapped continuation of the bullet above. Joined with a space,
      // because the newline is the file's margin, not the sentence's.
      open.body.push(line.trim());
      continue;
    }
    closeItem();
    if (line.trim() !== '' && current === null && headline === '') {
      headline = plain(line);
    }
  }
  closeItem();

  if (headline === '') throw new Error(`${version}.md has no headline paragraph`);
  if (sections.length === 0) throw new Error(`${version}.md has no ## sections`);
  return { version, headline, sections };
}

export function renderNotesModule(notes: ReleaseNotes): string {
  return (
    '// GENERATED by tools/build-desktop-notes.ts — do not edit.\n' +
    '// Source: docs/releases/' + notes.version + '.md\n' +
    '// Regenerate with: bun tools/build-desktop-notes.ts\n' +
    'export const RELEASE = {\n' +
    `  version: ${JSON.stringify(notes.version)},\n` +
    `  headline: ${JSON.stringify(notes.headline)},\n` +
    '  sections: [\n' +
    notes.sections
      .map(
        (section) =>
          '    {\n' +
          `      title: ${JSON.stringify(section.title)},\n` +
          '      items: [\n' +
          section.items
            .map(
              (item) =>
                `        { lead: ${JSON.stringify(item.lead)}, ` +
                `body: ${JSON.stringify(item.body)} },\n`,
            )
            .join('') +
          '      ],\n' +
          '    },\n',
      )
      .join('') +
    '  ],\n' +
    '};\n'
  );
}

if (import.meta.main) {
  const repo = join(import.meta.dir, '..');
  const version = JSON.parse(readFileSync(join(repo, 'package.json'), 'utf8')).version;
  const markdown = readFileSync(join(repo, 'docs', 'releases', `${version}.md`), 'utf8');
  writeFileSync(
    join(repo, 'desktop', 'ui', 'notes.js'),
    renderNotesModule(parseReleaseNotes(version, markdown)),
  );
  console.log(`wrote desktop/ui/notes.js from docs/releases/${version}.md`);
}
